version: '3.1'

services:

  server:
    build: 
      context: ./server
    container_name: server
    restart: always
    ports:
      - 50051:50051
    environment:
      - PORT=:50051

  # auth-svc:
  #   build: 
  #     context: ./auth-svc
  #   container_name: auth-svc
  #   restart: always
  #   ports:
  #     - 50051:50051




